// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: store.proto

package tech.claudioed.store.infra.proto;

public interface CardOrBuilder extends
    // @@protoc_insertion_point(interface_extends:store.Card)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string number = 1;</code>
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 1;</code>
   */
  com.google.protobuf.ByteString
      getNumberBytes();

  /**
   * <code>string expireAt = 2;</code>
   */
  java.lang.String getExpireAt();
  /**
   * <code>string expireAt = 2;</code>
   */
  com.google.protobuf.ByteString
      getExpireAtBytes();
}
