// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: store.proto

package tech.claudioed.store.infra.proto;

public interface PaymentResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:store.PaymentResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string processedAt = 2;</code>
   */
  java.lang.String getProcessedAt();
  /**
   * <code>string processedAt = 2;</code>
   */
  com.google.protobuf.ByteString
      getProcessedAtBytes();
}
