// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: store.proto

package tech.claudioed.store.infra.proto;

public final class Store {
  private Store() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_store_PaymentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_store_PaymentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_store_PaymentResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_store_PaymentResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_store_Card_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_store_Card_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_store_Order_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_store_Order_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_store_Customer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_store_Customer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013store.proto\022\005store\"{\n\016PaymentRequest\022\031" +
      "\n\004card\030\001 \001(\0132\013.store.Card\022\033\n\005order\030\002 \001(\013" +
      "2\014.store.Order\022!\n\010customer\030\003 \001(\0132\017.store" +
      ".Customer\022\016\n\006amount\030\004 \001(\002\"4\n\rPaymentResu" +
      "lt\022\016\n\006status\030\001 \001(\t\022\023\n\013processedAt\030\002 \001(\t\"" +
      "(\n\004Card\022\016\n\006number\030\001 \001(\t\022\020\n\010expireAt\030\002 \001(" +
      "\t\"&\n\005Order\022\016\n\006number\030\001 \001(\t\022\r\n\005total\030\002 \001(" +
      "\002\"6\n\010Customer\022\n\n\002id\030\001 \001(\t\022\020\n\010document\030\002 " +
      "\001(\t\022\014\n\004name\030\003 \001(\t2?\n\007Payment\0224\n\003pay\022\025.st" +
      "ore.PaymentRequest\032\024.store.PaymentResult",
      "\"\000B3\n tech.claudioed.store.infra.protoB\005" +
      "StoreP\001\242\002\005storeb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_store_PaymentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_store_PaymentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_store_PaymentRequest_descriptor,
        new java.lang.String[] { "Card", "Order", "Customer", "Amount", });
    internal_static_store_PaymentResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_store_PaymentResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_store_PaymentResult_descriptor,
        new java.lang.String[] { "Status", "ProcessedAt", });
    internal_static_store_Card_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_store_Card_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_store_Card_descriptor,
        new java.lang.String[] { "Number", "ExpireAt", });
    internal_static_store_Order_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_store_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_store_Order_descriptor,
        new java.lang.String[] { "Number", "Total", });
    internal_static_store_Customer_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_store_Customer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_store_Customer_descriptor,
        new java.lang.String[] { "Id", "Document", "Name", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
