// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authorization.proto

package tech.claudioed.authorization.infra.proto;

public final class Authorization {
  private Authorization() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authorization_PaymentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authorization_PaymentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authorization_PaymentResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authorization_PaymentResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authorization_Card_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authorization_Card_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_authorization_Order_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_authorization_Order_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023authorization.proto\022\rauthorization\"h\n\016" +
      "PaymentRequest\022!\n\004card\030\001 \001(\0132\023.authoriza" +
      "tion.Card\022#\n\005order\030\002 \001(\0132\024.authorization" +
      ".Order\022\016\n\006amount\030\003 \001(\002\"4\n\rPaymentResult\022" +
      "\016\n\006status\030\001 \001(\t\022\023\n\013processedAt\030\002 \001(\t\"(\n\004" +
      "Card\022\016\n\006number\030\001 \001(\t\022\020\n\010expireAt\030\002 \001(\t\"&" +
      "\n\005Order\022\016\n\006number\030\001 \001(\t\022\r\n\005total\030\002 \001(\0022O" +
      "\n\007Payment\022D\n\003pay\022\035.authorization.Payment" +
      "Request\032\034.authorization.PaymentResult\"\000B" +
      "K\n(tech.claudioed.authorization.infra.pr",
      "otoB\rAuthorizationP\001\242\002\rauthorizationb\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_authorization_PaymentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_authorization_PaymentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authorization_PaymentRequest_descriptor,
        new java.lang.String[] { "Card", "Order", "Amount", });
    internal_static_authorization_PaymentResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_authorization_PaymentResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authorization_PaymentResult_descriptor,
        new java.lang.String[] { "Status", "ProcessedAt", });
    internal_static_authorization_Card_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_authorization_Card_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authorization_Card_descriptor,
        new java.lang.String[] { "Number", "ExpireAt", });
    internal_static_authorization_Order_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_authorization_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_authorization_Order_descriptor,
        new java.lang.String[] { "Number", "Total", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
