// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authorization.proto

package tech.claudioed.authorization.infra.proto;

public interface OrderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:authorization.Order)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string number = 1;</code>
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 1;</code>
   */
  com.google.protobuf.ByteString
      getNumberBytes();

  /**
   * <code>float total = 2;</code>
   */
  float getTotal();
}
